### ISSUE TITLE
Negative variables under media queries

### ISSUE THREAD

**Issue by Dylan-Chapman** [jenius/rupture#58]
Hello,

I was having some issues with some styles not being compiled from my .styl file to .css and I think I narrowed it down to being Rupture. If you don't feel this is a Rupture issue, feel free to close.

I'm using Rupture with Gulp and have inside one of my .style files something along these lines:

```stylus
.menu-desktop
    display none
    +above("md")
        display block
        margin-left - $col-gutter
        margin-right - $col-gutter
```

When nested under the "+above" statement, the margin-left/-right don't get ouput to CSS. The CSS is output correctly in the follow scenarios:
- When they are removed from under the "+above" statement and placed under "display none", for example 
- If I remove the negative sign from the variables
- If I wrap the entire (- $col-gutter) in parenthesis
- If I put a colon after "margin-left" or "margin-right"

**Comment by declandewet** [comment]
Hi @Dylan-Chapman,

The issue you are experiencing here is not related to Rupture. It's a Stylus gotcha - When you have a left operand, followed by a space, followed by an operator, followed by a space and finally a right operand, Stylus will treat the line as a mathematical expression. The parser thinks your intension is to subtract `$col-gutter` from a variable called `margin-left`.

You can get around this as you've described above, as well as by leaving out the space between the minus sign and the variable. (`-$col-gutter`) This is probably the most ideal solution, since negative integers pretty much always never include whitespace.
